Draft: Implement a Scene Controller
kida31/untitled-plant-game pull request #45
Opened 2024-11-13 09:35 UTC by PsiLotY

closes #20

2025-01-08 20:41 UTC, Sui-nyan requested changes

2025-01-08 20:41 UTC, Sui-nyan commented on Features/Plants/Soil/SoilTile.cs
> +	// }
please remove comments if they unnecessary

2025-01-08 20:41 UTC, Sui-nyan commented on Features/NPC/VendingMachine/VendingMachineInteractable.cs
> +	// }
Please clean up unused code

2025-01-08 20:41 UTC, Sui-nyan commented on Features/SceneManager/SceneManager.cs
> +			//TODO: Load Map with bed in it
Is this TODO still relevant?

2025-01-08 20:41 UTC, Sui-nyan commented on Features/SceneManager/SceneManager.cs
> +		// });
Is this commented code still relevant?

2025-01-09 14:04 UTC, Sui-nyan commented on .gitignore
> -.apdisk
What's .apdisk and why does it need to be n gitinore? When I looked it up it says it's something from iPhone? Did u switch to apple @PsiLotY ?

2025-01-10 11:01 UTC, Sui-nyan requested changes
Change the node type of scenetransition, rest is looking better now

2025-01-10 11:01 UTC, Sui-nyan commented on Features/TeleportPlayer/SceneTransition.tscn
> +[node name="SceneTransition" type="CanvasLayer"]
Don't use a canvas layer in a Canvas Layer.
Since transition is inside the GUI which is a canvas layer already.
thank

2025-01-13 20:27 UTC, kida31 commented on Features/TeleportPlayer/SceneTransition.tscn
> +[node name="SceneTransition" type="CanvasLayer"]
Changed to control

2025-01-13 20:58 UTC, Sui-nyan approved these changes
Wow so the node type can be changed after all ⭐

2025-01-13 20:59 UTC, merged