clean up dialogue prefab
kida31/untitled-plant-game pull request #95
Opened 2024-11-20 20:49 UTC by Sui-nyan

2024-11-21 14:38 UTC, kida31 commented
Theres seems to be a small conflict with `main`.

please resolve merge conflicts @Sui-nyan

2024-11-21 15:04 UTC, kida31 requested changes

2024-11-24 17:16 UTC, kida31 approved these changes

2024-11-24 18:36 UTC, felix-schindler requested changes
Code looks a-okay, didn't try to run it tho. If you tested it and everything works you can merge.

Change the if-return thing or leave a comment telling me why you feel this is better, then I'll approve.

2024-11-24 18:36 UTC, felix-schindler commented on Features/Dialogue/DialogueUI.cs
> +		if (_currentDialogue == null)
Hier wären vllt `else-if` besser als immer zu returnen (irgendwann vergesse ich wann vllt schon returnt wurde)

2024-11-24 18:49 UTC, felix-schindler commented on Features/Dialogue/DialogueUI.cs
> +		if (_currentDialogue == null)
haben auf DC besprochen bleibt; zu viel Aufwand für ein readability-issue

2024-11-24 18:49 UTC, felix-schindler approved these changes

2024-11-24 18:50 UTC, merged